[2022-02-07T21:03:13Z] DEBUG    - Logging set up successfully
[2022-02-07T21:03:13Z] DEBUG    - Running generate: Namespace(version=False, subparser_name='generate', command=<function generate at 0x1172b65f0>, verbose=0)
[2022-02-07T21:03:13Z] DEBUG    - Root directory: /Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless
[2022-02-07T21:03:13Z] DEBUG    - Loading project file '/Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config'
[2022-02-07T21:03:13Z] DEBUG    - Project file /Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config not found. Have you run 'init' or in a wrong directory?
Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 442, in load
    self.load_settings()
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 195, in load_settings
    with self.settings_path.open("r", encoding="utf-8") as f:
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config'
[2022-02-07T21:03:13Z] DEBUG    - Caught exit recommendation
Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 442, in load
    self.load_settings()
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 195, in load_settings
    with self.settings_path.open("r", encoding="utf-8") as f:
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/generate.py", line 14, in generate
    project.load()
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 444, in load
    self._raise_invalid_project(
  File "/usr/local/Cellar/cloudformation-cli/0.2.22/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 190, in _raise_invalid_project
    raise InvalidProjectError(msg) from e
rpdk.core.exceptions.InvalidProjectError: Project file /Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config not found. Have you run 'init' or in a wrong directory?
[2022-02-07T21:03:13Z] CRITICAL - Project file /Users/aaratis/workplace/GitCFNPersonalFork/aws-cloudformation-resource-providers-iotwireless/.rpdk-config not found. Have you run 'init' or in a wrong directory?
